### ISSUE TITLE
inconsistent rendering

### ISSUE THREAD

**Issue by romaslmd** [Ridikon/ss-table#2]
```
# https://github.com/Ridikon/ss-table/blob/master/src/user-row/user-row.js
const renderProjects = () => {
		return projects.map((project, i) => {
			const {id, status, name, start, end, progress} = project;

			return (
				<tr key={id}>

					{renderProjectsName(i)} // <<<< що саме рендерить ф-ція?

					<td><a href="#">{name}</a></td>
					<td><span className={renderBadge(status)}>{status}</span></td>
					<td colSpan={numberOfMonth}>
						<div></div>
					</td>
				</tr>
			)
		})
	};
```

я так дивлюся що це табличка списку юзерів, але чому по рендерінгу ти береш вхід черех проекти

що відобразиться у таблиці якщо буде 2 юзера у яких немає проектів? або якщо будуть 2 юзера із проектом і 2 без - як буде рендеритись табличка?

спробуй переробити щось до вигляду 
```
const UserRow = ({ user, numberOfMonth }) => {
  //... code ...
  return(
    <tr key={user.id}>
      <td rowSpan={user.projects.length}>
        {renderAvatar(user)}
        {user.name}
      </td>
      {user.projects.map(renderProjectDetails)}
    </tr>
  });
{
```

**Comment by romaslmd** [comment]
попрацюй над форматуванням коду, дуже все стрибає

**Comment by Ridikon** [comment]
> ```
> # https://github.com/Ridikon/ss-table/blob/master/src/user-row/user-row.js
> const renderProjects = () => {
> 		return projects.map((project, i) => {
> 			const {id, status, name, start, end, progress} = project;
> 
> 			return (
> 				<tr key={id}>
> 
> 					{renderProjectsName(i)} // <<<< що саме рендерить ф-ція?
> 
> 					<td><a href="#">{name}</a></td>
> 					<td><span className={renderBadge(status)}>{status}</span></td>
> 					<td colSpan={numberOfMonth}>
> 						<div></div>
> 					</td>
> 				</tr>
> 			)
> 		})
> 	};
> ```
> 
> я так дивлюся що це табличка списку юзерів, але чому по рендерінгу ти береш вхід черех проекти
> 
> що відобразиться у таблиці якщо буде 2 юзера у яких немає проектів? або якщо будуть 2 юзера із проектом і 2 без - як буде рендеритись табличка?
> 
> спробуй переробити щось до вигляду
> 
> ```
> const UserRow = ({ user, numberOfMonth }) => {
>   //... code ...
>   return(
>     <tr key={user.id}>
>       <td rowSpan={user.projects.length}>
>         {renderAvatar(user)}
>         {user.name}
>       </td>
>       {user.projects.map(renderProjectDetails)}
>     </tr>
>   });
> {
> ```

**Comment by Ridikon** [comment]
`
render() {
		const { numberOfMonth, user } = this.props;
		const { progressColWidth, todayPosition } = this.state;

		return user.projects.map((project, i) => {
			const { id, status, name, start, end, progress } = project;

			const badgeClasses = ['badge', 'badge-pill', this.setClass(status, 'badge')];

			return (
				<tr key={id} className="user-row">
 // Тут я один раз роблю рендер ім'я і іконки юзера, так як проектів може бути багато
					{this.renderClientInfo(user, i)} 

					<td><a href="#" className="pl-3">{name}</a></td>
					<td><span className={badgeClasses.join(' ')}>{status}</span></td>
					<td
						className="progress-col"
						colSpan={numberOfMonth + 1}
						ref={this.progressRef}
					>
						<ProjectProgress
							bgClass={this.setClass(status, 'bg')}
							textClass={this.setClass(status, 'text')}
							colWidth={progressColWidth}
							numberOfMonth={numberOfMonth}
							start={start}
							end={end}
							progress={progress}
						/>
						<span
							style={{ left: `${todayPosition}px` }}
							className="bg-primary vertical-line"
						/>
					</td>
				</tr>
			)
		})
	}
`
Тут ситуація така, що передбачається наявність в юзера хочаб одного проекту, тому так зробив. Пробую пофіксити, але ті варіанти, що получаються, мені не подобаються. Хочу знайти більш елегантніше рішення.
В загальному я код порефакторив, старався зробити все культурно) 
Дякую за зауваження. Може ще щось знайдеться для покращення коду?

**Comment by Ridikon** [comment]
Ще є момент де потрібно вираховувати ширину кожної колонки з назвою місяця, для того щоб вони мали однакову ширину, щоб лінія котра показує сьогоднішній день правильно відображалася по шкалі. Рішення цьому теж є. Можна передавати пропсами з компонента де я беру референцію ширини поля, де малюються прогреси проектів і передавати вверх до хедера таблиці і там задавати по тій ширині, кожній колонці з назвою місяця однакову ширину. Або юзати редакс.

**Comment by romaslmd** [comment]
> Тут ситуація така, що передбачається наявність в юзера хочаб одного проекту, тому так зробив. 

недумаю що є такі ситуації, це виглядає табличка юзерів, і якщо немає даних - то думаю доцільніше було б відображати що їх немає

> В загальному я код порефакторив, старався зробити все культурно)

питання культури відносне, по написанню - непогано, проте буде іще краще без таких гіганських відступів, спробуй може іще додати кілька бібліотек - щоб скоротити код (напр `lodash`, `classNames` etc.)


старайся уникати непотрібних анонімних ф-нцій для разового рендерінгу, воно дає лиш лишні затрати - питання: значєш чому?

**Comment by romaslmd** [comment]
> Ще є момент де потрібно вираховувати ширину кожної колонки з назвою місяця, для того щоб вони мали однакову ширину, щоб лінія котра показує сьогоднішній день правильно відображалася по шкалі. 

а бутстрап тобі тоді для чого?

> Рішення цьому теж є. Можна передавати пропсами з компонента де я беру референцію ширини поля, де малюються прогреси проектів і передавати вверх до хедера таблиці і там задавати по тій ширині, кожній колонці з назвою місяця однакову ширину.

поки рішення небачу, зробиться тоді і мож буде побалакати. думаю іще багато приколів по дорозі надибаєш поки будеш то робити

> Або юзати редакс.

для чого ускладнювати?
