### ISSUE TITLE
func-based components

### ISSUE THREAD

**Issue by romaslmd** [Ridikon/ss-table#6]
немає резону створювати додаткові ф-ції в середині функції яку всеодно викликається

[file](https://github.com/Ridikon/ss-table/blob/master/src/components/project-progress/project-progress.js)
```
  function setStyles() {
    const styles = {};
    const oneDayWidth = colWidth / progressService.getDays(numberOfMonth);
    const startPosition = progressService.getPositionDay(start);
    const endPosition = progressService.getPositionDay(end);

    styles.left = (oneDayWidth * startPosition) + 'px';
    styles.width = ((oneDayWidth * endPosition) - (oneDayWidth * startPosition)) + 'px';

    return styles;
  }
```

**Comment by romaslmd** [comment]
```
if (bgClass) {
    clsBg.push(bgClass)
  }
```

+ модифікація константи

**Comment by romaslmd** [comment]
немає потреби робити тернарні умови для негативної частини при рендерінгу
`{progress ? `${progress}%` : ''}`
простіше взяти
`{!!progress && `${progress}%`}`

react не відображає `false`, `null`, `undefined` (! останні версії реакту)

**Comment by romaslmd** [comment]
і ф-ція `function setStyles() {` взагалі пекло, дуже важко прослідкувати що там відбувається
порефактори або краще забери її і порефактори розрахунок

**Comment by Ridikon** [comment]
> progress

**Comment by Ridikon** [comment]
> немає потреби робити тернарні умови для негативної частини при рендерінгу
> `{progress ? `${progress}%` : ''}`
> простіше взяти
> `{!!progress && `${progress}%`}`
> 
> react не відображає `false`, `null`, `undefined` (! останні версії реакту)

в такому випадку можна залишити просто `{progress && ${progress}%}`

**Comment by Ridikon** [comment]
> немає резону створювати додаткові ф-ції в середині функції яку всеодно викликається
> 
> [file](https://github.com/Ridikon/ss-table/blob/master/src/components/project-progress/project-progress.js)
> 
> ```
>   function setStyles() {
>     const styles = {};
>     const oneDayWidth = colWidth / progressService.getDays(numberOfMonth);
>     const startPosition = progressService.getPositionDay(start);
>     const endPosition = progressService.getPositionDay(end);
> 
>     styles.left = (oneDayWidth * startPosition) + 'px';
>     styles.width = ((oneDayWidth * endPosition) - (oneDayWidth * startPosition)) + 'px';
> 
>     return styles;
>   }
> ```

Що саме в цій ф-ції не так?
